#!/bin/bash

if [ "$#" -ne 5 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

###########################
####### SVN
# SVN repository to be migrated
COMPANY=$1
SVN_HOST=$2
SVN_USER=$3
SVN_PASSWORD=$4

####### Project name #######
PROJECT_NAME=$5

BASE_SVN="$SVN_HOST/$PROJECT_NAME"
SVN_ARGS=" --non-interactive --username=$SVN_USER --password=$SVN_PASSWORD"

####### Removes slashes from the project name and replace it with underscore
PROJECT_NAME=${PROJECT_NAME//[\/]/_}

###########################
#### Don't need to change from here
###########################

# Geral Configuration
ABSOLUTE_PATH=$(pwd)
TMP=$ABSOLUTE_PATH/"migration-"$PROJECT_NAME

AUTHORS=$PROJECT_NAME"-authors.txt"

if [ ! -d "$TMP" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir $TMP
fi

cd $TMP

echo
echo '[LOG] Getting authors'
svn log -q $BASE_SVN $SVN_ARGS | awk -v domain=$COMPANY -F '|' '/^r/ {sub("^ ", "", $2); sub(" $", "", $2); print $2" = "$2" <"$2"@"domain">"}' | sort -u >> $AUTHORS

echo "Authors file [$AUTHORS] created!"
