#!/bin/bash

if [ "$#" -ne 11 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

###########################
####### SVN
# SVN repository to be migrated
SVN_HOST=$1
SVN_USER=$2
SVN_PASSWORD=$3
SVN_BRANCHES=$4
SVN_TAGS=$5
SVN_TRUNK=$6

####### Project name #######
PROJECT_NAME=${11}

BASE_SVN="$SVN_HOST/$PROJECT_NAME"
SVN_ARGS=" --non-interactive --username=$SVN_USER --password=$SVN_PASSWORD"

####### Removes slashes from the project name and replace it with underscore
PROJECT_NAME=${PROJECT_NAME//[\/]/_}

###########################
####### GIT
# Git repository to migrate
GIT_URL="$8://$9@$7/$9/${PROJECT_NAME}.git"

# Geral Configuration
ABSOLUTE_PATH=$(pwd)
TMP=$ABSOLUTE_PATH/"migration-"$PROJECT_NAME

# Branchs Configuration
SVN_BRANCHES=$BASE_SVN/$SVN_BRANCHES
SVN_TAGS=$BASE_SVN/$SVN_TAGS
SVN_TRUNK=$BASE_SVN/$SVN_TRUNK

echo '[LOG] Starting migration of '$SVN_TRUNK
echo '[LOG] Using: '$(git --version)
echo '[LOG] Using: '$(svn --version | grep svn,)

if [ ! -d "$TMP" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir $TMP
fi

cd $TMP

echo
echo '[LOG] Getting SSL certificates'
svn info $BASE_SVN $SVN_ARGS

echo
echo '[LOG] Getting first revision'
FIRST_REVISION=$( svn log -r 1:HEAD --limit 1 $BASE_SVN $SVN_ARGS | awk -F '|' '/^r/ {sub("^ ", "", $1); sub(" $", "", $1); print $1}' )

echo
echo '[RUN] git svn fetch -'$FIRST_REVISION':HEAD'
git svn fetch -$FIRST_REVISION:HEAD

# Cache the credentials
git config credential.helper 'cache --timeout=3600'

echo
echo '[RUN] git remote add origin '$GIT_URL
git remote add origin $GIT_URL

echo
echo '[RUN] create local branches matching subversion'
for BRANCH in $(svn ls $SVN_BRANCHES); do
    echo git branch ${BRANCH%/} remotes/${BRANCH%/}
    git branch ${BRANCH%/} remotes/${BRANCH%/}
done

echo '[RUN] create tags matching subversion'
git for-each-ref --format="%(refname:short) %(objectname)" refs/remotes/origin/tags  |
while read BRANCH REF
do
    TAG_NAME=${BRANCH#*/}
    BODY="$(git log -1 --format=format:%B $REF)"

    echo "ref=$REF parent=$(git rev-parse $REF^) tagname=$TAG_NAME body=$BODY" >&2

    git tag -a -m "$BODY" $TAG_NAME $REF^  && git branch -r -d $BRANCH
done


push() {
    # Keep the ignore settings
    git svn show-ignore -i trunk > .gitignore
    git add .gitignore
    git commit -m 'Convert svn:ignore properties to .gitignore.'

    # Removes the validation of SSL certs
    git config --global http.sslVerify false

    # Reassign the branches
    cp -rf .git/refs/remotes/origin/tags/* .git/refs/tags/
    rm -rf .git/refs/remotes/origin/tags
    cp -rf .git/refs/remotes/origin/* .git/refs/heads/
    rm -rf .git/refs/remotes/origin

    # Delete the branch trunk
    git branch -d trunk

    # Push to remote all the branches and tags
    git push origin --all
    git push origin --tags

    OUTPUT=$?
}
echo
echo '[RUN] git push'

# Call the function to push
push
if [[ $OUTPUT -eq 0 ]]; then
    echo 'Sucessufull.'
else
    echo 'Error!'
fi
